### ISSUE TITLE
Getting error with workflow

### ISSUE THREAD

**Issue by Seifood** [faoliveira78/android_device_oneplus_cheeseburger#1]
Hi I'm trying to build twrp-12.1 with ur workflow but getting an error could u check in Actions tab tree name is zeus

**Comment by faoliveira78** [comment]
Sorry for the delay in responding, but I was only able to build it after I cherry-pick the fscrypt patch.  Take my most current script from this tree https://github.com/faoliveira78/android_device_oneplus_cheeseburger_dumpling and pull out the second LineageOS cherry-pick that should work for you.

**Comment by faoliveira78** [comment]
> Hi I'm trying to build twrp-12.1 with ur workflow but getting an error could u check in Actions tab tree name is zeus

**Comment by Seifood** [comment]
> Sorry for the delay in responding, but I was only able to build it after I cherry-pick the fscrypt patch. Take my most current script from this tree https://github.com/faoliveira78/android_device_oneplus_cheeseburger_dumpling and pull out the second LineageOS cherry-pick that should work for you.


I have already did that but got same issue is there a way i can message u my telegram username is @Droneship

**Comment by faoliveira78** [comment]
Dude, I forked your tree (https://github.com/faoliveira78/device_xiaomi_zeus-TWRP/actions) and ran the script but got the same error. So I googled and found that this error is due to lack of RAM. Github actions only have 8Gb available, which doesn't seem to be enough to compile for your device. I tried reducing the jobs as suggested on that page (https://stackoverflow.com/questions/58894290/android-opensource-project-build-error-failed-out-soon-build-ninja) but it didn't work either. On this other page another guy suggests using swap memory and posted a script for it (https://github.community/t/can-you-help-to-give-more-memory-on-some-project/17892/3 ) but not tested. This will probably help you.

**Comment by Seifood** [comment]
> Dude, I forked your tree (https://github.com/faoliveira78/device_xiaomi_zeus-TWRP/actions) and ran the script but got the same error. So I googled and found that this error is due to lack of RAM. Github actions only have 8Gb available, which doesn't seem to be enough to compile for your device. I tried reducing the jobs as suggested on that page (https://stackoverflow.com/questions/58894290/android-opensource-project-build-error-failed-out-soon-build-ninja) but it didn't work either. On this other page another guy suggests using swap memory and posted a script for it (https://github.community/t/can-you-help-to-give-more-memory-on-some-project/17892/3 ) but not tested. This will probably help you.

Okay gonna try thx

**Comment by Seifood** [comment]
How can i contact you ? Do u have telegram?
